feat: remove check end-epoch and fix kurtosis version

diff --git a/scripts/local_config_aggchain_proof_gen b/scripts/local_config_aggchain_proof_gen
--- a/scripts/local_config_aggchain_proof_gen
+++ b/scripts/local_config_aggchain_proof_gen
@@ -137,14 +137,11 @@ function export_obj_key_from_toml_file() {
 
 ###############################################################################
 function export_values_from_combined_json() {
-    local combined_json_file="/opt/zkevm/combined.json"
-    local contracts_service_wrapper="kurtosis service exec $KURTOSIS_ENCLAVE contracts-001"
-    combined_json_output=$($contracts_service_wrapper "cat $combined_json_file" | tail -n +2)
-    
-    export zkevm_L2_bridge_address=$(echo "$combined_json_output" | jq -r .polygonZkEVML2BridgeAddress)
-    export zkevm_global_exit_root_l2_address=$(echo "$combined_json_output" | jq -r .polygonZkEVMGlobalExitRootL2Address)
-
-    echo "$combined_json_output"
+    local _COMBINED_JSON_FILE=$1
+    export zkevm_L2_bridge_address=$(cat $_COMBINED_JSON_FILE | jq -r .polygonZkEVML2BridgeAddress)
+    ok_or_fatal "Error getting polygonZkEVML2BridgeAddress from combined_json_file: $_COMBINED_JSON_FILE"
+    export zkevm_global_exit_root_l2_address=$(cat $_COMBINED_JSON_FILE | jq -r .polygonZkEVMGlobalExitRootL2Address)
+    ok_or_fatal "Error getting polygonZkEVMGlobalExitRootL2Address from combined_json_file: $_COMBINED_JSON_FILE"
 }
 
 ###############################################################################
@@ -256,6 +253,29 @@ function create_dest_folder() {
     mkdir $zkevm_path_rw_data
 }
 ###############################################################################
+function kurtosis_download_file_exec_method() {
+    local _FILE=$1
+    local _SERVICE=$2
+    local _DEST_FILE=$3
+    local _IS_JSON=$4
+    if [ $# -lt 3 ]; then
+        log_fatal "Error: kurtosis_download_file_exec_method: missing parameters  (file, service, dest_file)"
+        exit 1
+    fi
+    kurtosis service exec $KURTOSIS_ENCLAVE $_SERVICE  "cat $_FILE" > $_DEST_FILE
+    # This is a workarround!, versions 0.1.
+    local KURTOSIS_VERSION=$(kurtosis version | cut -d ':'  -f 2 | head -n 1)
+    dpkg --compre-versions "$KURTOSIS_VERSION" "ge" "1.7.0" >/dev/null
+    if [ $? -eq 0 ]; then
+        echo "detected kurtosis version >= 1.7.0. So the output of the file don't need adjustment"
+    else
+        echo "detected kurtosis version < 1.7.0. So the output of the file need to remove first line because it's debug"
+        mv $_DEST_FILE $_DEST_FILE.original
+        cat $_DEST_FILE.original | tail -n +2 > $_DEST_FILE
+    fi
+
+}
+###############################################################################
 function download_kurtosis_artifacts() {
     kurtosis files download $KURTOSIS_ENCLAVE sovereign_genesis $DEST
     ok_or_fatal "Error downloading kurtosis artifact sovereign_genesis to $DEST"
@@ -267,6 +287,10 @@ function download_kurtosis_artifacts() {
 
     kurtosis files download $KURTOSIS_ENCLAVE cdk-aggoracle-config-artifact $DEST
     ok_or_fatal "Error downloading kurtosis artifact cdk-aggoracle-config  to $DEST"
+
+    kurtosis_download_file_exec_method "/opt/zkevm/combined.json" "contracts-001" "$DEST/combined.json"
+    ok_or_fatal "Error downloading kurtosis artifact combined.json  to $DEST"
+    export combined_json_file=$DEST/combined.json
 }
 ###############################################################################
 function check_generated_config_file() {
