feat: remove check end-epoch and fix kurtosis version (#424)
- Removed aggsender param `MaxEpochPercentageAllowedToSendCertificate`   
- Support kurtosis-core >=1.7.0
- Fix #434:  fails to setup L2 client with op-node support for finalized

diff --git a/scripts/local_config_aggchain_proof_gen b/scripts/local_config_aggchain_proof_gen
--- a/scripts/local_config_aggchain_proof_gen
+++ b/scripts/local_config_aggchain_proof_gen
@@ -137,14 +137,16 @@ function export_obj_key_from_toml_file() {
 
 ###############################################################################
 function export_values_from_combined_json() {
-    local combined_json_file="/opt/zkevm/combined.json"
-    local contracts_service_wrapper="kurtosis service exec $KURTOSIS_ENCLAVE contracts-001"
-    combined_json_output=$($contracts_service_wrapper "cat $combined_json_file" | tail -n +2)
-    
-    export zkevm_L2_bridge_address=$(echo "$combined_json_output" | jq -r .polygonZkEVML2BridgeAddress)
-    export zkevm_global_exit_root_l2_address=$(echo "$combined_json_output" | jq -r .polygonZkEVMGlobalExitRootL2Address)
-
-    echo "$combined_json_output"
+    log_debug "export_values_from_combined_json"
+    local _COMBINED_JSON_FILE=$1
+    if [ -z "$_COMBINED_JSON_FILE" ]; then
+        log_fatal "Error: export_values_from_combined_json: missing parameter (combined_json_file)"
+    fi
+    export zkevm_L2_bridge_address=$(cat $_COMBINED_JSON_FILE | jq -r .polygonZkEVML2BridgeAddress)
+    ok_or_fatal "Error getting polygonZkEVML2BridgeAddress from combined_json_file: $_COMBINED_JSON_FILE"
+    export zkevm_global_exit_root_l2_address=$(cat $_COMBINED_JSON_FILE | jq -r .polygonZkEVMGlobalExitRootL2Address)
+    ok_or_fatal "Error getting polygonZkEVMGlobalExitRootL2Address from combined_json_file: $_COMBINED_JSON_FILE"
+    log_debug "export_values_from_combined_json... finished"
 }
 
 ###############################################################################
@@ -208,10 +210,12 @@ function export_ports_from_kurtosis() {
     export_portnum_from_kurtosis_or_fail zkevm_rpc_http_port op-el-1-op-geth-op-node-001 rpc rpc
     export_portnum_from_kurtosis_or_fail agglayer_grpc_port agglayer aglr-grpc
     export_portnum_from_kurtosis_or_fail aggkit_prover_grpc_port aggkit-prover grpc
+    export_portnum_from_kurtosis_or_fail op_cl_rpc_port op-cl-1-op-node-op-geth-001 http
     export l1_rpc_url="http://localhost:${l1_rpc_port}"
     export l2_rpc_url="http://localhost:${zkevm_rpc_http_port}"
     export agglayer_grpc_url="http://localhost:${agglayer_grpc_port}"
     export aggkit_prover_grpc_url="http://localhost:${aggkit_prover_grpc_port}"
+    export op_cl_rpc_url="http://localhost:${op_cl_rpc_port}"
 }
 
 ###############################################################################
@@ -256,6 +260,29 @@ function create_dest_folder() {
     mkdir $zkevm_path_rw_data
 }
 ###############################################################################
+function kurtosis_download_file_exec_method() {
+    local _FILE=$1
+    local _SERVICE=$2
+    local _DEST_FILE=$3
+    local _IS_JSON=$4
+    if [ $# -lt 3 ]; then
+        log_fatal "Error: kurtosis_download_file_exec_method: missing parameters  (file, service, dest_file)"
+        exit 1
+    fi
+    kurtosis service exec $KURTOSIS_ENCLAVE $_SERVICE  "cat $_FILE" > $_DEST_FILE
+    # This is a workarround!, versions 0.1.
+    local KURTOSIS_VERSION=$(kurtosis version | cut -d ':'  -f 2 | head -n 1)
+    dpkg --compare-versions "$KURTOSIS_VERSION" "ge" "1.7.0" >/dev/null
+    if [ $? -eq 0 ]; then
+        echo "detected kurtosis version >= 1.7.0. So the output of the file don't need adjustment $(wc -l $_DEST_FILE)"
+    else
+        echo "detected kurtosis version < 1.7.0. So the output of the file need to remove first line because it's debug $(wc -l $_DEST_FILE)"
+        mv $_DEST_FILE $_DEST_FILE.original
+        cat $_DEST_FILE.original | tail -n +2 > $_DEST_FILE
+        wc -l $_DEST_FILE
+    fi
+}
+###############################################################################
 function download_kurtosis_artifacts() {
     kurtosis files download $KURTOSIS_ENCLAVE sovereign_genesis $DEST
     ok_or_fatal "Error downloading kurtosis artifact sovereign_genesis to $DEST"
@@ -267,6 +294,10 @@ function download_kurtosis_artifacts() {
 
     kurtosis files download $KURTOSIS_ENCLAVE cdk-aggoracle-config-artifact $DEST
     ok_or_fatal "Error downloading kurtosis artifact cdk-aggoracle-config  to $DEST"
+
+    kurtosis_download_file_exec_method "/opt/zkevm/combined.json" "contracts-001" "$DEST/combined.json"
+    ok_or_fatal "Error downloading kurtosis artifact combined.json  to $DEST"
+    export combined_json_file=$DEST/combined.json
 }
 ###############################################################################
 function check_generated_config_file() {
@@ -310,9 +341,9 @@ rm -Rf tmp/aggkit/runtime/*
 check_requirements
 create_dest_folder
 
-download_kurtosis_artifacts
+download_kurtosis_artifacts 
 
-export_values_from_combined_json
+export_values_from_combined_json $combined_json_file
 export_ports_from_kurtosis
 export_values_of_cdk_node_config $DEST/config.toml
 export_forced_values
