aggoracle committee testing

diff --git a/.github/workflows/test-e2e.yml b/.github/workflows/test-e2e.yml
--- a/.github/workflows/test-e2e.yml
+++ b/.github/workflows/test-e2e.yml
@@ -54,7 +54,7 @@ jobs:
             fi
           else
             # For push/workflow_dispatch, use the fixed commit
-            COMMIT="b5d03b89954f785c973f54c94b65f6f5101fff5f"
+            COMMIT="1fec85d7aee3c64e6d768b5dbb0a5a79e520900d"
             echo "Using fixed kurtosis-cdk commit: ${COMMIT}"
           fi
           echo "commit=${COMMIT}" >> $GITHUB_OUTPUT
@@ -69,8 +69,10 @@ jobs:
     name: Read aggkit args
     runs-on: ubuntu-latest
     outputs:
-      # single l2 network (fork 12, op-succinct)
-      kurtosis-cdk-args-single-fork12-op-succinct: ${{ steps.read-args.outputs.fork12_op_succinct_args }}
+      # single l2 network (op-succinct)
+      kurtosis-cdk-args-single-op-succinct: ${{ steps.read-args.outputs.op_succinct_args }}
+      # single l2 network (op-succinct with aggoracle committee)
+      kurtosis-cdk-args-single-op-succinct-aggoracle-committee: ${{ steps.read-args.outputs.op_succinct_aggoracle_committee_args }}
       # single l2 network (fork 12, pessimistic)
       kurtosis-cdk-args-single-fork12-pessimistic: ${{ steps.read-args.outputs.fork12_pessimistic_args }}
       # single l2 network (fork 12, global index pp old contracts)
@@ -89,8 +91,11 @@ jobs:
         id: read-args
         run: |
           # single l2 network (fork 12, op-succinct)
-          CONTENT=$(cat ./.github/test_e2e_single_chain_fork12_op_succinct_args.json | jq -c .)
-          echo "fork12_op_succinct_args=${CONTENT}" >> $GITHUB_OUTPUT
+          CONTENT=$(cat ./.github/test_e2e_single_chain_op_succinct_args.json | jq -c .)
+          echo "op_succinct_args=${CONTENT}" >> $GITHUB_OUTPUT
+          # single l2 network (fork 12, op-succinct with aggoracle committee)
+          CONTENT=$(cat ./.github/test_e2e_single_chain_op_succinct_aggoracle_committee_args.json | jq -c .)
+          echo "op_succinct_aggoracle_committee_args=${CONTENT}" >> $GITHUB_OUTPUT
           # single l2 network (fork 12, pessimistic)
           CONTENT=$(jq -s '.[0] * .[1]' ./.github/test_e2e_cdk_args_base.json ./.github/test_e2e_gas_token_enabled_args.json | jq -c .)
           echo "fork12_pessimistic_args=${CONTENT}" >> $GITHUB_OUTPUT
@@ -138,11 +143,11 @@ jobs:
       - build-aggkit-image
       - read-aggkit-args
       - get-kurtosis-cdk-commit
-    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@71c4ab572fab2a871e0336af20bd13cfb2ecba97
+    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@a34e6272c6c9023d8c105214bd630fd6c22681a8
     secrets: inherit
     with:
       kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
-      agglayer-e2e-ref: 71c4ab572fab2a871e0336af20bd13cfb2ecba97
+      agglayer-e2e-ref: a34e6272c6c9023d8c105214bd630fd6c22681a8
       kurtosis-cdk-enclave-name: aggkit
       kurtosis-cdk-args: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-single-fork12-pessimistic }}
       test-name: "test-single-l2-network-fork12-pessimistic"
@@ -152,7 +157,6 @@ jobs:
     name: Check results for single l2 network (pessimistic)
     needs:
       - test-single-l2-network-fork12-pessimistic
-    if: always()
     runs-on: ubuntu-latest
     steps:
       - run: exit 1
@@ -165,12 +169,12 @@ jobs:
       - build-tools
       - read-aggkit-args
       - get-kurtosis-cdk-commit
-    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@71c4ab572fab2a871e0336af20bd13cfb2ecba97
+    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@a34e6272c6c9023d8c105214bd630fd6c22681a8
     secrets: inherit
     if: always() && github.event_name == 'schedule' && github.ref == 'refs/heads/develop'
     with:
       kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
-      agglayer-e2e-ref: 71c4ab572fab2a871e0336af20bd13cfb2ecba97
+      agglayer-e2e-ref: a34e6272c6c9023d8c105214bd630fd6c22681a8
       kurtosis-cdk-enclave-name: aggkit
       kurtosis-cdk-args: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-single-fork12-global-index-pp-old-contracts }}
       test-name: "test-single-l2-network-fork12-global-index-pp-old-contracts"
@@ -181,37 +185,63 @@ jobs:
     name: Check results for single l2 network (global index pp old contracts)
     needs:
       - test-single-l2-network-fork12-global-index-pp-old-contracts
-    if: always()
+    if: always() && github.event_name == 'schedule' && github.ref == 'refs/heads/develop'
     runs-on: ubuntu-latest
     steps:
       - run: exit 1
         if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-single-l2-network-fork12-global-index-pp-old-contracts.result) }}
 
-  test-single-l2-network-fork12-op-succinct:
+  test-single-l2-network-op-succinct:
     name: Single L2 chain tests (op-succinct)
     needs:
       - build-aggkit-image
       - read-aggkit-args
       - get-kurtosis-cdk-commit
-    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@71c4ab572fab2a871e0336af20bd13cfb2ecba97
+    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@a34e6272c6c9023d8c105214bd630fd6c22681a8
     secrets: inherit
     with:
       kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
-      agglayer-e2e-ref: 71c4ab572fab2a871e0336af20bd13cfb2ecba97
+      agglayer-e2e-ref: a34e6272c6c9023d8c105214bd630fd6c22681a8
       kurtosis-cdk-enclave-name: op
-      kurtosis-cdk-args: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-single-fork12-op-succinct }}
-      test-name: "test-single-l2-network-fork12-op-succinct"
+      kurtosis-cdk-args: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-single-op-succinct }}
+      test-name: "test-single-l2-network-op-succinct"
       event-name: ${{ github.event_name }}
 
-  check-single-network-fork12-op-succinct-tests-result:
+  check-single-network-op-succinct-tests-result:
     name: Check results for single l2 network (op-succinct)
     needs:
-      - test-single-l2-network-fork12-op-succinct
-    if: always()
+      - test-single-l2-network-op-succinct
     runs-on: ubuntu-latest
     steps:
       - run: exit 1
-        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-single-l2-network-fork12-op-succinct.result) }}
+        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-single-l2-network-op-succinct.result) }}
+
+  test-single-l2-network-op-succinct-aggoracle-committee:
+    name: Single L2 chain tests (op-succinct with aggoracle committee)
+    needs:
+      - build-aggkit-image
+      - read-aggkit-args
+      - get-kurtosis-cdk-commit
+    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@a34e6272c6c9023d8c105214bd630fd6c22681a8
+    secrets: inherit
+    if: always() && github.event_name == 'schedule' && github.ref == 'refs/heads/develop'
+    with:
+      kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
+      agglayer-e2e-ref: a34e6272c6c9023d8c105214bd630fd6c22681a8
+      kurtosis-cdk-enclave-name: op
+      kurtosis-cdk-args: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-single-op-succinct-aggoracle-committee }}
+      test-name: "test-single-l2-network-op-succinct-aggoracle-committee"
+      event-name: ${{ github.event_name }}
+
+  check-single-l2-network-op-succinct-aggoracle-committee-tests-result:
+    name: Check results for single l2 network (op-succinct with aggoracle committee)
+    needs:
+      - test-single-l2-network-op-succinct-aggoracle-committee
+    if: always() && github.event_name == 'schedule' && github.ref == 'refs/heads/develop'
+    runs-on: ubuntu-latest
+    steps:
+      - run: exit 1
+        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-single-l2-network-op-succinct-aggoracle-committee.result) }}
 
   test-multi-l2-networks-2-chains:
     name: Multi chains E2E test (2 chains)
@@ -220,11 +250,11 @@ jobs:
       - build-tools
       - read-aggkit-args
       - get-kurtosis-cdk-commit
-    uses: agglayer/e2e/.github/workflows/aggkit-e2e-multi-chains.yml@71c4ab572fab2a871e0336af20bd13cfb2ecba97
+    uses: agglayer/e2e/.github/workflows/aggkit-e2e-multi-chains.yml@a34e6272c6c9023d8c105214bd630fd6c22681a8
     secrets: inherit
     with:
       kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
-      agglayer-e2e-ref: 71c4ab572fab2a871e0336af20bd13cfb2ecba97
+      agglayer-e2e-ref: a34e6272c6c9023d8c105214bd630fd6c22681a8
       kurtosis-cdk-enclave-name: aggkit
       aggsender-find-imported-bridge-artifact: aggsender_find_imported_bridge
       kurtosis-cdk-args-1: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-1 }}
@@ -239,41 +269,44 @@ jobs:
       - run: exit 1
         if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-multi-l2-networks-2-chains.result) }}
 
-  test-multi-l2-networks-3-chains:
-    name: Multi chains E2E test (3 chains)
-    needs:
-      - build-aggkit-image
-      - build-tools
-      - read-aggkit-args
-      - get-kurtosis-cdk-commit
-    uses: agglayer/e2e/.github/workflows/aggkit-e2e-multi-chains.yml@71c4ab572fab2a871e0336af20bd13cfb2ecba97
-    secrets: inherit
-    with:
-      kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
-      agglayer-e2e-ref: 71c4ab572fab2a871e0336af20bd13cfb2ecba97
-      kurtosis-cdk-enclave-name: aggkit
-      aggsender-find-imported-bridge-artifact: aggsender_find_imported_bridge
-      kurtosis-cdk-args-1: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-3 }}
-      kurtosis-cdk-args-2: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-4 }}
-      kurtosis-cdk-args-3: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-5 }}
-      number-of-chains: 3
+  # test-multi-l2-networks-3-chains:
+  #   name: Multi chains E2E test (3 chains)
+  #   needs:
+  #     - build-aggkit-image
+  #     - build-tools
+  #     - read-aggkit-args
+  #     - get-kurtosis-cdk-commit
+  #   uses: agglayer/e2e/.github/workflows/aggkit-e2e-multi-chains.yml@a34e6272c6c9023d8c105214bd630fd6c22681a8
+  #   if: always() && github.event_name == 'schedule' && github.ref == 'refs/heads/develop'
+  #   secrets: inherit
+  #   with:
+  #     kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
+  #     agglayer-e2e-ref: a34e6272c6c9023d8c105214bd630fd6c22681a8
+  #     kurtosis-cdk-enclave-name: aggkit
+  #     aggsender-find-imported-bridge-artifact: aggsender_find_imported_bridge
+  #     kurtosis-cdk-args-1: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-3 }}
+  #     kurtosis-cdk-args-2: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-4 }}
+  #     kurtosis-cdk-args-3: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-5 }}
+  #     number-of-chains: 3
 
-  check-multi-l2-networks-3-chains-tests-result:
-    name: Check results for multi l2 networks (3 chains)
-    needs:
-      - test-multi-l2-networks-3-chains
-    runs-on: ubuntu-latest
-    steps:
-      - run: exit 1
-        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-multi-l2-networks-3-chains.result) }}
+  # check-multi-l2-networks-3-chains-tests-result:
+  #   name: Check results for multi l2 networks (3 chains)
+  #   needs:
+  #     - test-multi-l2-networks-3-chains
+  #   if: always() && github.event_name == 'schedule' && github.ref == 'refs/heads/develop'
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - run: exit 1
+  #       if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-multi-l2-networks-3-chains.result) }}
 
   notify-slack:
     name: Notify Slack
     needs:
       - test-single-l2-network-fork12-pessimistic
-      - test-single-l2-network-fork12-op-succinct
+      - test-single-l2-network-op-succinct
+      - test-single-l2-network-op-succinct-aggoracle-committee
       - test-multi-l2-networks-2-chains
-      - test-multi-l2-networks-3-chains
+      # - test-multi-l2-networks-3-chains
       - test-single-l2-network-fork12-global-index-pp-old-contracts
       - get-kurtosis-cdk-commit
     runs-on: ubuntu-latest
@@ -291,7 +324,8 @@ jobs:
 
             Test Results:
             • Single L2 (pessimistic): ${{ needs.test-single-l2-network-fork12-pessimistic.result == 'success' && '🟢' || '🔴' }}
-            • Single L2 (op-succinct): ${{ needs.test-single-l2-network-fork12-op-succinct.result == 'success' && '🟢' || '🔴' }}
+            • Single L2 (op-succinct): ${{ needs.test-single-l2-network-op-succinct.result == 'success' && '🟢' || '🔴' }}
+            • Single L2 (op-succinct with aggoracle committee): ${{ needs.test-single-l2-network-op-succinct-aggoracle-committee.result == 'success' && '🟢' || '🔴' }}
             • Multi L2 (2 chains): ${{ needs.test-multi-l2-networks-2-chains.result == 'success' && '🟢' || '🔴' }}
             • Multi L2 (3 chains): ${{ needs.test-multi-l2-networks-3-chains.result == 'success' && '🟢' || '🔴' }}
             • Single L2 (global index pp old contracts): ${{ needs.test-single-l2-network-fork12-global-index-pp-old-contracts.result == 'success' && '🟢' || '🔴' }}
