aggoracle committee testing

diff --git a/.github/workflows/test-e2e.yml b/.github/workflows/test-e2e.yml
--- a/.github/workflows/test-e2e.yml
+++ b/.github/workflows/test-e2e.yml
@@ -54,7 +54,7 @@ jobs:
             fi
           else
             # For push/workflow_dispatch, use the fixed commit
-            COMMIT="1fec85d7aee3c64e6d768b5dbb0a5a79e520900d"
+            COMMIT="26adf30f4bcae4640081351a0a5c159e2e22a22d"
             echo "Using fixed kurtosis-cdk commit: ${COMMIT}"
           fi
           echo "commit=${COMMIT}" >> $GITHUB_OUTPUT
@@ -143,11 +143,11 @@ jobs:
       - build-aggkit-image
       - read-aggkit-args
       - get-kurtosis-cdk-commit
-    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@a34e6272c6c9023d8c105214bd630fd6c22681a8
+    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@b89e67587388ddf57c992b9113b28ef1d90ee8ef
     secrets: inherit
     with:
       kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
-      agglayer-e2e-ref: a34e6272c6c9023d8c105214bd630fd6c22681a8
+      agglayer-e2e-ref: b89e67587388ddf57c992b9113b28ef1d90ee8ef
       kurtosis-cdk-enclave-name: aggkit
       kurtosis-cdk-args: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-single-fork12-pessimistic }}
       test-name: "test-single-l2-network-fork12-pessimistic"
@@ -169,12 +169,12 @@ jobs:
       - build-tools
       - read-aggkit-args
       - get-kurtosis-cdk-commit
-    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@a34e6272c6c9023d8c105214bd630fd6c22681a8
+    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@b89e67587388ddf57c992b9113b28ef1d90ee8ef
     secrets: inherit
     if: always() && github.event_name == 'schedule' && github.ref == 'refs/heads/develop'
     with:
       kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
-      agglayer-e2e-ref: a34e6272c6c9023d8c105214bd630fd6c22681a8
+      agglayer-e2e-ref: b89e67587388ddf57c992b9113b28ef1d90ee8ef
       kurtosis-cdk-enclave-name: aggkit
       kurtosis-cdk-args: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-single-fork12-global-index-pp-old-contracts }}
       test-name: "test-single-l2-network-fork12-global-index-pp-old-contracts"
@@ -197,11 +197,11 @@ jobs:
       - build-aggkit-image
       - read-aggkit-args
       - get-kurtosis-cdk-commit
-    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@a34e6272c6c9023d8c105214bd630fd6c22681a8
+    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@b89e67587388ddf57c992b9113b28ef1d90ee8ef
     secrets: inherit
     with:
       kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
-      agglayer-e2e-ref: a34e6272c6c9023d8c105214bd630fd6c22681a8
+      agglayer-e2e-ref: b89e67587388ddf57c992b9113b28ef1d90ee8ef
       kurtosis-cdk-enclave-name: op
       kurtosis-cdk-args: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-single-op-succinct }}
       test-name: "test-single-l2-network-op-succinct"
@@ -222,12 +222,12 @@ jobs:
       - build-aggkit-image
       - read-aggkit-args
       - get-kurtosis-cdk-commit
-    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@a34e6272c6c9023d8c105214bd630fd6c22681a8
+    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@b89e67587388ddf57c992b9113b28ef1d90ee8ef
     secrets: inherit
     if: always() && github.event_name == 'schedule' && github.ref == 'refs/heads/develop'
     with:
       kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
-      agglayer-e2e-ref: a34e6272c6c9023d8c105214bd630fd6c22681a8
+      agglayer-e2e-ref: b89e67587388ddf57c992b9113b28ef1d90ee8ef
       kurtosis-cdk-enclave-name: op
       kurtosis-cdk-args: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-single-op-succinct-aggoracle-committee }}
       test-name: "test-single-l2-network-op-succinct-aggoracle-committee"
@@ -243,31 +243,31 @@ jobs:
       - run: exit 1
         if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-single-l2-network-op-succinct-aggoracle-committee.result) }}
 
-  test-multi-l2-networks-2-chains:
-    name: Multi chains E2E test (2 chains)
-    needs:
-      - build-aggkit-image
-      - build-tools
-      - read-aggkit-args
-      - get-kurtosis-cdk-commit
-    uses: agglayer/e2e/.github/workflows/aggkit-e2e-multi-chains.yml@a34e6272c6c9023d8c105214bd630fd6c22681a8
-    secrets: inherit
-    with:
-      kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
-      agglayer-e2e-ref: a34e6272c6c9023d8c105214bd630fd6c22681a8
-      kurtosis-cdk-enclave-name: aggkit
-      aggsender-find-imported-bridge-artifact: aggsender_find_imported_bridge
-      kurtosis-cdk-args-1: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-1 }}
-      kurtosis-cdk-args-2: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-2 }}
+  # test-multi-l2-networks-2-chains:
+  #   name: Multi chains E2E test (2 chains)
+  #   needs:
+  #     - build-aggkit-image
+  #     - build-tools
+  #     - read-aggkit-args
+  #     - get-kurtosis-cdk-commit
+  #   uses: agglayer/e2e/.github/workflows/aggkit-e2e-multi-chains.yml@b89e67587388ddf57c992b9113b28ef1d90ee8ef
+  #   secrets: inherit
+  #   with:
+  #     kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
+  #     agglayer-e2e-ref: b89e67587388ddf57c992b9113b28ef1d90ee8ef
+  #     kurtosis-cdk-enclave-name: aggkit
+  #     aggsender-find-imported-bridge-artifact: aggsender_find_imported_bridge
+  #     kurtosis-cdk-args-1: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-1 }}
+  #     kurtosis-cdk-args-2: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-2 }}
 
-  check-multi-l2-networks-2-chains-tests-result:
-    name: Check results for multi l2 networks (2 chains)
-    needs:
-      - test-multi-l2-networks-2-chains
-    runs-on: ubuntu-latest
-    steps:
-      - run: exit 1
-        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-multi-l2-networks-2-chains.result) }}
+  # check-multi-l2-networks-2-chains-tests-result:
+  #   name: Check results for multi l2 networks (2 chains)
+  #   needs:
+  #     - test-multi-l2-networks-2-chains
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - run: exit 1
+  #       if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-multi-l2-networks-2-chains.result) }}
 
   # test-multi-l2-networks-3-chains:
   #   name: Multi chains E2E test (3 chains)
@@ -276,12 +276,12 @@ jobs:
   #     - build-tools
   #     - read-aggkit-args
   #     - get-kurtosis-cdk-commit
-  #   uses: agglayer/e2e/.github/workflows/aggkit-e2e-multi-chains.yml@a34e6272c6c9023d8c105214bd630fd6c22681a8
+  #   uses: agglayer/e2e/.github/workflows/aggkit-e2e-multi-chains.yml@b89e67587388ddf57c992b9113b28ef1d90ee8ef
   #   if: always() && github.event_name == 'schedule' && github.ref == 'refs/heads/develop'
   #   secrets: inherit
   #   with:
   #     kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
-  #     agglayer-e2e-ref: a34e6272c6c9023d8c105214bd630fd6c22681a8
+  #     agglayer-e2e-ref: b89e67587388ddf57c992b9113b28ef1d90ee8ef
   #     kurtosis-cdk-enclave-name: aggkit
   #     aggsender-find-imported-bridge-artifact: aggsender_find_imported_bridge
   #     kurtosis-cdk-args-1: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-3 }}
@@ -305,7 +305,7 @@ jobs:
       - test-single-l2-network-fork12-pessimistic
       - test-single-l2-network-op-succinct
       - test-single-l2-network-op-succinct-aggoracle-committee
-      - test-multi-l2-networks-2-chains
+      # - test-multi-l2-networks-2-chains
       # - test-multi-l2-networks-3-chains
       - test-single-l2-network-fork12-global-index-pp-old-contracts
       - get-kurtosis-cdk-commit
